INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (7, 1, 1, 1);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (4, 1, 0, 0);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (6, 1, 1, 0);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (5, 1, 0, 1);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (3, 0, 1, 1);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (2, 0, 1, 0);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (1, 0, 0, 1);
INSERT INTO ENABLE_BLOG (ENA_ID, ENA_TO_WATCH, ENA_TO_COMMENT, ENA_TO_WRITE) VALUES (0, 0, 0, 0);

COMMIT WORK;
