INSERT INTO GROUPP (GROUP_ID, NAME, DESCRIPTION, DATE_OF_CREATE, MEMBERS, ADMINNS) VALUES (90, 'Beautiful illustrations.', 'You can find here a lot of illstrations.', '2013-12-13', 1, 6);
INSERT INTO GROUPP (GROUP_ID, NAME, DESCRIPTION, DATE_OF_CREATE, MEMBERS, ADMINNS) VALUES (56, 'Literature.', 'For people who like reading.', '2014-06-26', 3, 7);
INSERT INTO GROUPP (GROUP_ID, NAME, DESCRIPTION, DATE_OF_CREATE, MEMBERS, ADMINNS) VALUES (89, 'Music.', 'A lot of new music here.', '2013-01-15', 4, 3);
INSERT INTO GROUPP (GROUP_ID, NAME, DESCRIPTION, DATE_OF_CREATE, MEMBERS, ADMINNS) VALUES (67, 'Haters.', 'no comment', '2013-10-07', 5, 7);
INSERT INTO GROUPP (GROUP_ID, NAME, DESCRIPTION, DATE_OF_CREATE, MEMBERS, ADMINNS) VALUES (96, 'Players.', 'For people who like online games.', '2013-09-23', 3, 1);

COMMIT WORK;
