INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (1, 1);
INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (2, 2);
INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (3, 3);
INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (4, 4);
INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (5, 5);
INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (6, 6);
INSERT INTO PRIVACY_POST (PRIV_ID, ENA_POST) VALUES (7, 7);

COMMIT WORK;
