INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (134, 0);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (1, 1);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (2, 2);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (3, 3);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (4, 4);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (5, 5);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (6, 6);
INSERT INTO PRIVACY_BLOG (PRIV_ID, ENA_BLOG) VALUES (7, 7);

COMMIT WORK;
